Develop
SpicyW0lf/tinkoffhw1 pull request #3
Opened 2023-10-01 18:40 UTC by SpicyW0lf

Third homework

2023-10-03 10:19 UTC, EMDavl requested changes

2023-10-03 10:19 UTC, EMDavl commented on fintechspring/src/main/java/com/example/fintechspring/DTO/WeatherDTO.java
> +        this.date = LocalDateTime.parse(date, DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));
Форматтер можно вынести в константу класса

2023-10-03 10:19 UTC, EMDavl commented on fintechspring/src/main/java/com/example/fintechspring/controllers/WeatherController.java
> +                mapper.writeValueAsString(weathers.stream()
Обычно возвращают ResponseEntity<Класс>, оно само замапится в Json. Самостоятельно этого делать не требуется

2023-10-03 10:19 UTC, EMDavl commented on fintechspring/src/main/java/com/example/fintechspring/controllers/WeatherController.java
> +                        .filter(it -> it.getName().equals(city) && it.getDate().toLocalDate().equals(date))
Принято выносить логику в сервисы, оставляя контроллерам только обслуживание запросов: получить запрос, отправить какой-то ответ.

Это помогает абстрагироваться от способа получения данных и повышает возможность переиспользования кода, т.е не важно откуда к тебе пришел запрос Rest / Soap / т.д. тебе не надо повторно писать реализацию, ты просто делегируешь запрос в сервис. Ну и взаимодействие с БД соответственно переносится на уровень репозитория

https://stackoverflow.com/a/38678061/16006138
https://stackoverflow.com/a/9633619/16006138

2023-10-03 10:19 UTC, EMDavl commented on fintechspring/src/main/java/com/example/fintechspring/controllers/WeatherController.java
> +        if (weather.getDate() == null || weather.getName() == null || weather.getTemperature() == null) {
Зачастую, для валидации используют Hibernate Validator, в spring boot проект его можно подключить, добавив стартер [spring-boot-starter-validation](https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-validation)

В этой домашке на баллы не влияет, просто держу в курсе

2023-10-03 10:19 UTC, EMDavl commented on fintechspring/src/main/java/com/example/fintechspring/controllers/WeatherController.java
> +            throw new NullException();
Нейминг кажется не очень удачным. Не сразу понятно, что этот exception кидается при невалидном инпуте

2023-10-03 10:19 UTC, EMDavl commented on fintechspring/src/main/java/com/example/fintechspring/controllers/WeatherController.java
> +    public ResponseEntity<Map<String, String>> postWeather(@RequestBody WeatherDTO weather, @Parameter(description = "Название города") @PathVariable String city) throws NullException {
Кмк лучше сделать какую-нибудь DTO, вроде MessageDto / MethodResultDto / BaseDto / и т.д. В котором будет поле `String message`.

Это позволит повысить читабельность: сразу понятно что возвращается в методе и не надо думать а че это за мапа такая, что в ней будет потом. Сформировать доменную область, описать для класса документацию в том же сваггере

2023-10-03 10:19 UTC, EMDavl commented on fintechspring/src/main/java/com/example/fintechspring/controllers/WeatherController.java
> +                return ResponseEntity.badRequest()
Можно кинуть ошибку и обработать в ExceptionHandler'е оставив контроллеру работу с "успешным" случаем

2023-10-03 10:19 UTC, EMDavl commented on fintechspring/src/main/java/com/example/fintechspring/controllers/WeatherController.java
> +                    return ResponseEntity.badRequest().body(Map.of("message","You cant update temperature, its the same!"));
PUT идемпотентный метод, так что при повторном запросе с аналогичными данными мы не должны выкидывать ошибку

2023-10-03 10:19 UTC, EMDavl commented on fintechspring/src/main/java/com/example/fintechspring/controllers/WeatherController.java
> +    public ResponseEntity<Map<String, String>> nullError() {
Также можно сделать что-то вроде ExceptionMessage или заюзать то что ты создашь пока будешь резолвить предыдущий коммент.

Обычно ExceptionHandler'ы выносят в отдельный класс так и "натравливают" на пакет с контроллерами
![image](https://github.com/SpicyW0lf/tinkoffhw1/assets/79557554/90250986-98f0-4b3b-bde4-37f7021cf197)

Это позволяет одинаково обрабатывать ошибки, независимо от того какой контроллер их бросил

2023-10-03 10:19 UTC, EMDavl commented on fintechspring/src/main/java/com/example/fintechspring/controllers/WeatherController.java
> +}
Также надо добавить кастомную обработку 500 ошибок (Exception.class)

2023-10-04 18:54 UTC, SpicyW0lf commented on fintechspring/src/main/java/com/example/fintechspring/DTO/WeatherDTO.java
> +        this.date = LocalDateTime.parse(date, DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));
Сделал

2023-10-04 18:54 UTC, SpicyW0lf commented on fintechspring/src/main/java/com/example/fintechspring/controllers/WeatherController.java
> +                mapper.writeValueAsString(weathers.stream()
Сделал

2023-10-04 18:55 UTC, SpicyW0lf commented on fintechspring/src/main/java/com/example/fintechspring/controllers/WeatherController.java
> +                        .filter(it -> it.getName().equals(city) && it.getDate().toLocalDate().equals(date))
Сделал

2023-10-04 18:55 UTC, SpicyW0lf commented on fintechspring/src/main/java/com/example/fintechspring/controllers/WeatherController.java
> +        if (weather.getDate() == null || weather.getName() == null || weather.getTemperature() == null) {
Принял к сведению

2023-10-04 18:55 UTC, SpicyW0lf commented on fintechspring/src/main/java/com/example/fintechspring/controllers/WeatherController.java
> +            throw new NullException();
Поменял

2023-10-04 18:55 UTC, SpicyW0lf commented on fintechspring/src/main/java/com/example/fintechspring/controllers/WeatherController.java
> +    public ResponseEntity<Map<String, String>> postWeather(@RequestBody WeatherDTO weather, @Parameter(description = "Название города") @PathVariable String city) throws NullException {
Сделал

2023-10-04 18:55 UTC, SpicyW0lf commented on fintechspring/src/main/java/com/example/fintechspring/controllers/WeatherController.java
> +                return ResponseEntity.badRequest()
Сделал

2023-10-04 18:55 UTC, SpicyW0lf commented on fintechspring/src/main/java/com/example/fintechspring/controllers/WeatherController.java
> +                    return ResponseEntity.badRequest().body(Map.of("message","You cant update temperature, its the same!"));
Исправил

2023-10-04 18:55 UTC, SpicyW0lf commented on fintechspring/src/main/java/com/example/fintechspring/controllers/WeatherController.java
> +    public ResponseEntity<Map<String, String>> nullError() {
Сделал

2023-10-04 18:56 UTC, SpicyW0lf commented on fintechspring/src/main/java/com/example/fintechspring/controllers/WeatherController.java
> +}
Сделал

2023-10-05 07:52 UTC, EMDavl commented on fintechspring/src/main/java/com/example/fintechspring/controllers/WeatherController.java
> +            throw new BadArgumentsException("This wheather is already exists, if you want to change it use PUT method");
В целом такие ошибки тоже в сервис лучше переносить, в createWeather'е спрятать например и более общий текст сообщения `This wheather is already exists`, без привязки к конкретному способу коммуникации (REST / grpc и т.д.)

В рамках этой домашки на баллы не влияет

2023-10-05 07:52 UTC, EMDavl approved these changes

2023-10-05 09:18 UTC, merged