homework4 done
SpicyW0lf/tinkoffhw1 pull request #4
Opened 2023-10-08 19:15 UTC by SpicyW0lf

2023-10-08 19:18 UTC, SpicyW0lf commented on fintechspring/src/main/java/com/example/fintechspring/controllers/WeatherController.java
> +    }
Пришлось запихнуть в контроллер, иначе все перехватывал хэндлер Exception.class

2023-10-08 19:22 UTC, SpicyW0lf commented on fintechspring/src/main/java/com/example/fintechspring/controllers/WeatherController.java
Пришлось хэндлер для ошибок из RestTemplate перенести сюда, иначе их всех перехватывал хэндлер Exception.class

2023-10-12 14:36 UTC, EMDavl requested changes

2023-10-12 14:36 UTC, EMDavl commented on fintechspring/src/main/java/com/example/fintechspring/configs/Config.java
> +    public Function<String, ApiResponse> rateLimitFunction(WeatherApiService client, @Value("${weather-api.limit}") int limit) {
Еще есть [адаптированная под spring boot версия resilence4j](https://resilience4j.readme.io/docs/getting-started-3), где все можно через конфиги настраивать и аннотацией отметить какой метод как лимитить. 

Вообще идея с такой функцией мне не очень нравится, т.к. становится неочевидно где это используется ну и с ООП не особо стыкуется, это уже попахивает функциональщиной. Имхо лучше сделать сервис-прослойку и через него вызывать, либо в самом клиенте обернуть вызов в этот метод

2023-10-12 14:36 UTC, EMDavl commented on fintechspring/src/main/resources/application.yaml
> +  token: 77513508c9594d5aa0490823230810
Надеюсь токен не реальный?)
Лучше заменить на переменную окружения например:

```
weather-api:
    token: ${TOKEN}
    ...
```

2023-10-12 14:36 UTC, EMDavl commented on fintechspring/src/main/java/com/example/fintechspring/controllers/WeatherController.java
Попытался разобраться с причиной, т.к. поведение выглядит странным и вот что нашел:

Из документации `@ControllerAdvice`:

```
For @ExceptionHandler methods, a root exception match will be preferred to just matching a cause of the current exception, among the handler methods of a particular advice bean. However, a cause match on a higher-priority advice will still be preferred over any match (whether root or cause level) on a lower-priority advice bean. As a consequence, please declare your primary root exception mappings on a prioritized advice bean with a corresponding order.
```

Как это связано с твоей ошибкой:
Ты унаследовал `WeatherApiException` от `IOException`. Если пройти по стеку вызовов с момента выброса твоей ошибки и вниз до метода `RestTemplate.doExecute(url, uriTemplate, method, requestCallback, responseExtractor)`, то увидим такое (скрин): 
![image](https://github.com/SpicyW0lf/tinkoffhw1/assets/79557554/77000078-8c41-46bd-92bd-014521b7f06a)

Т.е. дальше у тебя уже пробрасывается не `WeatherApiException` (далее WAE), а `ResourceAccessException` (далее RAE) с cause = <твоя ошибка>. Т.к. в контроллере у тебя нет обработчика для RAE и выше, но есть обработчик для RAE.cause, то он и используется т.к. обработчик в контроллере это тот самый `higher-priority advice`. Если ты добавишь в контроллер хендлер для Exception'а, то у тебя опять будет использоваться хендлер для RAE ака хендлер Exception.class

2023-10-12 14:36 UTC, EMDavl commented on fintechspring/src/main/java/com/example/fintechspring/controllers/WeatherController.java
Мое предложение - сделать WAE наследником RuntimeException, т.к. он выбрасывается не при IOException (что-то не так с получением запроса и т.п.) а при определенных HTTP кодах 4хх, 5хх

2023-10-12 14:36 UTC, EMDavl commented on fintechspring/src/main/java/com/example/fintechspring/controllers/WeatherController.java
> +        return ResponseEntity.ok(weatherDTO);
Призываю все уносить в сервисы делая контроллер максимально простым. В идеале что-то вида

```
    @GetMapping("/weather")
    @Operation(summary = "Получить погоду с Api", description = "Получить погоду по городу с внешнего сервиса")
    public ResponseEntity<WeatherDTO> check(@RequestParam String city) {
        return ResponseEntity.ok(weatherService.getCurrentWeatherForCity(city));
 }
```

2023-10-12 14:36 UTC, EMDavl commented on fintechspring/src/main/java/com/example/fintechspring/controllers/WeatherController.java
> +    public ResponseEntity<ResponseDTO> weatherApiException(WeatherApiException ex) {
Фикс этой проблемы описал выше, необходимо исправить

2023-10-12 20:09 UTC, SpicyW0lf commented on fintechspring/src/main/java/com/example/fintechspring/controllers/WeatherController.java
Интересная штука с advice-ми и их приоритетами. Сделал WAE наследником, теперь все ок.

2023-10-12 20:09 UTC, SpicyW0lf commented on fintechspring/src/main/java/com/example/fintechspring/configs/Config.java
> +    public Function<String, ApiResponse> rateLimitFunction(WeatherApiService client, @Value("${weather-api.limit}") int limit) {
Сделал

2023-10-12 20:10 UTC, SpicyW0lf commented on fintechspring/src/main/resources/application.yaml
> +  token: 77513508c9594d5aa0490823230810
Сделал)

2023-10-12 20:10 UTC, SpicyW0lf commented on fintechspring/src/main/java/com/example/fintechspring/controllers/WeatherController.java
> +        return ResponseEntity.ok(weatherDTO);
Поправил

2023-10-12 20:10 UTC, SpicyW0lf commented on fintechspring/src/main/java/com/example/fintechspring/controllers/WeatherController.java
> +    public ResponseEntity<ResponseDTO> weatherApiException(WeatherApiException ex) {
Исправил

2023-10-15 16:26 UTC, merged