homework5 done
SpicyW0lf/tinkoffhw1 pull request #5
Opened 2023-10-21 15:52 UTC by SpicyW0lf

2023-10-23 12:41 UTC, EMDavl requested changes
Основное замечание - переделать JDBC репозиторий на чистый JDBC

2023-10-23 12:41 UTC, EMDavl commented on fintechspring/src/main/java/com/example/fintechspring/controllers/WeatherHiberController.java
> +    public List<City> findCities(@PathVariable String city) {
Лучше использовать не Entity, а отдельную DTO (в целом в контроллерах)

2023-10-23 12:41 UTC, EMDavl commented on fintechspring/src/main/java/com/example/fintechspring/controllers/WeatherHiberController.java
> +public class WeatherHiberController {
В этой задаче не принципиально, но лучше вырабатывать привычку документировать API swagger'ом

2023-10-23 12:41 UTC, EMDavl commented on fintechspring/src/main/java/com/example/fintechspring/models/WeatherEntity.java
> +public class WeatherEntity {
Постфикс Entity излишен, т.к. по пакету понятно для чего класс

2023-10-23 12:41 UTC, EMDavl commented on fintechspring/src/main/java/com/example/fintechspring/repositories/JDBC/CityJDBCRepo.java
> +        return jdbcTemplate.query(
В лекции на 71 минуте было про то что надо на чистом JDBC

2023-10-23 12:41 UTC, EMDavl commented on fintechspring/src/main/java/com/example/fintechspring/services/WeatherHiberService.java
> +        City city1 = cityRepositoty.findByNameAndDate(city.getName(), city.getDate()).orElseThrow(NoSuchElementException::new);
Лучше давать более говорящие названия. Аргумент поменять на cityRequest, а это уже пусть будет city, например

2023-10-23 12:41 UTC, EMDavl commented on fintechspring/src/main/resources/db/changelog/changeset/create-tables-v1.yaml
> +              - column:
Кажется, что правильнее не одна погода - много городов, а один город - много замеров погоды

2023-10-23 12:41 UTC, EMDavl commented on fintechspring/src/main/java/com/example/fintechspring/services/WeatherHiberService.java
> +}
Лучше разбить на несколько сервисов по сущностям weather и city. Т.к. WeatherService не очень много общего имеет с созданием новых городов, например.

2023-10-23 15:53 UTC, SpicyW0lf commented on fintechspring/src/main/java/com/example/fintechspring/repositories/JDBC/CityJDBCRepo.java
> +        return jdbcTemplate.query(
![image](https://github.com/SpicyW0lf/tinkoffhw1/assets/62665736/a16458fd-d5da-40b1-94b9-2d026bff0229)

Понял. Увидел в чате эти сообщения и, раз никто из преподавателей не опроверг, подумал, что так можно.

2023-10-31 11:29 UTC, SpicyW0lf commented on fintechspring/src/main/java/com/example/fintechspring/controllers/WeatherHiberController.java
> +    public List<City> findCities(@PathVariable String city) {
Понял, а после лекции по безопасности стало еще понятнее)

2023-10-31 11:29 UTC, SpicyW0lf commented on fintechspring/src/main/java/com/example/fintechspring/controllers/WeatherHiberController.java
> +public class WeatherHiberController {
Учту

2023-10-31 11:29 UTC, SpicyW0lf commented on fintechspring/src/main/java/com/example/fintechspring/services/WeatherHiberService.java
> +        City city1 = cityRepositoty.findByNameAndDate(city.getName(), city.getDate()).orElseThrow(NoSuchElementException::new);
Согласен, поменял

2023-11-01 12:26 UTC, merged